name: webserver
description: A minimal web server.
# version: 1.0.0

environment:
  sdk: '2.12.1'

dependencies:
  path: 
  shelf: 
  shelf_static: 
  shelf_router: 
  crypto: 
dev_dependencies:
  http: 
  test: