name: pubserver
description: A minimal pub server.
# version: 1.0.0

environment:
  sdk: '2.12.1'

dependencies:
  path: 
  shelf: 
  shelf_static: 
  shelf_router: 
  crypto: 
  dart_jsonwebtoken: ^2.0.1
dev_dependencies:
  test:
  http: 